### ISSUE TITLE
Fix generate registration options view

### ISSUE THREAD

**Issue by bn-s** [Charles-Rocke/bn-s#1]
Took a quick look at your project. The first thing I notice is the return of a standard Django `HttpResponse` on what I assume is meant to be an API endpoint.

If you want to stick with standard Django, convert this to a `JsonResponse`. However, I noticed you seem to be heading towards DRF, so what you should do is:
1) Import DRF's `Response` and `apiview` decorator.
2) Decorate `handler_generate_registration_options()` with the `apiview` decorator and return a DRF `Response` from it.

This would look like (with everything that's already there cut out):

```
...
from rest_framework.decorators import api_view
from rest_framework.response import Response
...

@api_view()
def handler_generate_registration_options(request):
    ...
    return Response(json_opts)
```

You should hopefully now get the expected return.

**Comment by Charles-Rocke** [comment]
@bn-s Hey what's up Benjamin, thanks for coming! And ok I've just fixed it and its working properly. My next problem is getting the models set up to remembering users on registration. I used a `@dataclass` in flask just to get it working quickly (terrible idea but it worked). I'm currently setting up the models now.

**Comment by Charles-Rocke** [comment]
@bn-s If you want, I've set up a new branch and will be continuing there. It's named after your account to make it easy to find.
